#check50:
#  checks:
#    hello world:
#      - run: ./hello
#        stdout: Hello, world!
#        exit: 0

#submit50:
#  checks:
#    hello world:
#      - run:  ./hello
#        stdout: Hello, world!
#        exit: 0
check50: 
  files: &check50_files
    - !exclude "*"
    - !require hello.c

submit50:
  files: *check50_files